version: "3.8"

# Volumes
volumes:
       
  www:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${SERVER_PATH}/www/

services:
  # PHP Service
  php:
    build: 
      context: ./php/
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - "www:/var/www/html"

  # Apache Service
  apache:
    build: './apache/'
    depends_on:
      - php
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - "www:/var/www/html"

  # MariaDB Service
  mariadb:
    build:
      context: ./mariadb
      args:
        - MARIADB_VERSION=${MARIADB_VERSION}
        
    environment:
      - ALLOW_EMPTY_PASSWORD=${MARIADB_ALLOW_EMPTY_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_CHARACTER_SET=${MARIADB_CHARACTER_SET}
      - MARIADB_COLLATE=${MARIADB_COLLATE}

    volumes:
      - "./mariadb/mariarestore.sh:/docker-entrypoint-initdb.d/mariarestore.sh"
      - "./mariadb/db-dump:/docker-entrypoint-initdb.d/db-dump"

  # phpMyAdmin Service
  phpmyadmin:
    image: ${PMA_IMAGE}:${PMA_VERSION}
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${PMA_HOST}
    depends_on:
      - mariadb

  # MongoDB Service
  mongodb:
    container_name: ${ME_CONFIG_MONGODB_SERVER}
    image: ${MONGO_IMAGE}:${MONGO_VERSION}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - "./mongodb/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh"
      - "./mongodb/db-dump:/docker-entrypoint-initdb.d/db-dump"

  # Mongo Express Service
  mongo-express:
    image: ${MONGO_EXPRESS_IMAGE}:${MONGO_EXPRESS_VERSION}
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    depends_on:
      - ${ME_CONFIG_MONGODB_SERVER}
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_SERVER}://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      

